TEXT_MAIN_TITLE = 'Platforma transakcyjna Future Station'
TEXT_MAIN_DESCRIPTION = 'Biuro maklerskie William-Scott Trade'
TEXT_CLOSE_BUTTON = 'Wyjdź'
TEXT_AMOUNT = 'Kwota'

COLOUR_BACKGROUND = '#2A2A2E'
COLOUR_TEXT = '#FAFAFA'

FONT_TYPEFACE = 'Arial'
TITLE_FONT_WEIGHT = 'bold'
FONT_SIZE_TITLE = 20
FONT_SIZE_DESCRIPTION = 14
FONT_SIZE_REGULAR = 12
