TEXT_MAIN_TITLE = 'Platforma transakcyjna Future Station'
TEXT_MAIN_DESCRIPTION = 'Biuro maklerskie William-Scott Trade'
TEXT_CLOSE_BUTTON = 'Wyjdź'
# TEXT_CONFIRM_BUTTON = 'Zatwierdź'
TEXT_WITHDRAW_BUTTON = 'Wypłać'
TEXT_DEPOSIT_BUTTON = 'Wpłać'
TEXT_AMOUNT = 'Kwota'

COLOUR_BACKGROUND = '#2A2A2E'
COLOUR_TEXT = '#FAFAFA'

FONT_TYPEFACE = 'Arial'
FONT_WEIGHT_TITLE = 'bold'
FONT_SIZE_TITLE = 20
FONT_SIZE_DESCRIPTION = 14
FONT_SIZE_REGULAR = 12

ERROR_MESSAGE_VALUE = 'Podano nieprawidłową wartość'

STATE_DEPOSIT = 'deposit'
STATE_WITHDRAWAL = 'withdrawal'